name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Python Dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip==23.2  # تثبيت الإصدار المستقر من pip
        pip install -r requirements.txt

    - name: Install Buildozer and Android dependencies
      run: |
        sudo apt update
        sudo apt install -y libgl1-mesa-dev openjdk-11-jdk unzip wget
        source venv/bin/activate
        pip install buildozer cython

    - name: Download and setup Android SDK
      run: |
        # إنشاء الدليل إذا لم يكن موجودًا
        mkdir -p $HOME/Android/Sdk/cmdline-tools

        # تحميل أدوات Android SDK
        wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -O sdk-tools-linux.zip

        # استخراج الأدوات إلى الدليل المناسب
        unzip sdk-tools-linux.zip -d $HOME/Android/Sdk/cmdline-tools
        mv $HOME/Android/Sdk/cmdline-tools/cmdline-tools $HOME/Android/Sdk/cmdline-tools/latest

        # إعداد المسار
        echo "export ANDROID_SDK_ROOT=$HOME/Android/Sdk" >> $GITHUB_ENV
        echo "export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$PATH" >> $GITHUB_ENV

    - name: Accept Android SDK licenses and install packages
      run: |
        source $GITHUB_ENV
        yes | sdkmanager --licenses
        sdkmanager "platform-tools" "platforms;android-31" "build-tools;31.0.0" "ndk;21.3.6528147"

    - name: Build APK
      run: |
        source venv/bin/activate
        buildozer init
        buildozer android debug

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4.3.4
      with:
        name: apk-build-artifact
        path: |
          ./*.apk
          .buildozer/android/platform/build/dists/*/bin/*.apk
