name: Build APK

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
  workflow_dispatch:

env:
  BUILD_NUMBER: 1
  BUILD_VERSION: 1.0.0
  PYTHON_VERSION: 3.10  # استخدام Python 3.10
  FLUTTER_VERSION: 3.22.2

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}

    - name: Setup Java JDK
      uses: actions/setup-java@v4.2.1
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Install Android SDK dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y wget unzip
        wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
        mkdir -p $HOME/android-sdk/cmdline-tools
        unzip -q commandlinetools-linux-8512546_latest.zip -d $HOME/android-sdk/cmdline-tools
        mv $HOME/android-sdk/cmdline-tools/cmdline-tools $HOME/android-sdk/cmdline-tools/tools
        echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
        echo "PATH=$HOME/android-sdk/cmdline-tools/tools/bin:$HOME/android-sdk/platform-tools:$PATH" >> $GITHUB_ENV
        source $GITHUB_ENV
        yes | sdkmanager --licenses
        sdkmanager "platform-tools" "platforms;android-31" "build-tools;31.0.0"

    - name: Install Buildozer and Cython
      run: |
        pip install buildozer
        pip install cython==0.29.24

    - name: Prepare buildozer
      run: |
        buildozer init
        # إزالة أي إعدادات مكررة
        sed -i '/^title =/d' buildozer.spec
        sed -i '/^package.name =/d' buildozer.spec
        sed -i '/^package.domain =/d' buildozer.spec
        sed -i '/^requirements =/d' buildozer.spec
        sed -i '/^source.include_exts =/d' buildozer.spec
        # إضافة إعدادات جديدة
        echo "title = My Flet App" >> buildozer.spec
        echo "package.name = myfletapp" >> buildozer.spec
        echo "package.domain = org.example" >> buildozer.spec
        echo "requirements = flet, opencv-python, numpy, Pillow, httpx, easyocr" >> buildozer.spec
        echo "source.include_exts = py,png,jpg,jpeg,kv,ttf,xml" >> buildozer.spec

    - name: Build APK
      run: |
        buildozer -v android debug

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: apk-build-artifact
        path: bin/*.apk
        if-no-files-found: warn
        overwrite: false
