name: Build Flet App for Android

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Android dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y openjdk-11-jdk wget unzip
        wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
        mkdir -p $HOME/android-sdk/cmdline-tools
        unzip commandlinetools-linux-8512546_latest.zip -d $HOME/android-sdk/cmdline-tools
        mv $HOME/android-sdk/cmdline-tools/cmdline-tools $HOME/android-sdk/cmdline-tools/tools
        echo "export ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
        echo "export PATH=$HOME/android-sdk/cmdline-tools/tools/bin:$HOME/android-sdk/platform-tools:$PATH" >> $GITHUB_ENV
        source $GITHUB_ENV
        yes | sdkmanager --licenses
        sdkmanager "platform-tools" "platforms;android-31" "build-tools;31.0.0"

    - name: Prepare buildozer
      run: |
        pip install buildozer
        buildozer init
        sed -i 's/# (str) Title of your application/title = My Flet App/' buildozer.spec
        sed -i 's/# (str) Package name/package.name = myfletapp/' buildozer.spec
        sed -i 's/# (str) Package domain/package.domain = org.example/' buildozer.spec
        sed -i 's/# (list) Application requirements/requirements = flet, opencv-python, numpy, Pillow, httpx, easyocr/' buildozer.spec
        sed -i 's/# (str) Source code URL (if any)/source.include_exts = py,png,jpg,jpeg,kv,ttf,xml/' buildozer.spec

    - name: Build APK
      run: |
        buildozer -v android debug

    - name: Upload APK to Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: my-flet-app-apk
        path: bin/*.apk
